# This rule is not used by the project rbac-subtract itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the rbac.kim.karolinska.se.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rbac-subtract
    app.kubernetes.io/managed-by: kustomize
  name: modifyclusterrole-editor-role
rules:
- apiGroups:
  - rbac.kim.karolinska.se
  resources:
  - modifyclusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.kim.karolinska.se
  resources:
  - modifyclusterroles/status
  verbs:
  - get
