---
apiVersion: kim.karolinska.se/v1
kind: ModifyClusterRole
metadata:
  name: kim-edit
spec:
  clusterRole: edit
  removeRules:
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - '*'
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
