apiVersion: rbac.kim.karolinska.se/v1
kind: ModifyClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rbac-subtract
    app.kubernetes.io/managed-by: kustomize
  name: modifyclusterrole-sample
spec:
  clusterRole: view
  removeRules:
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - '*'
