apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-role
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: kim.karolinska.se/v1
kind: ModifyClusterRole
metadata:
  name: my-modifed-role
spec:
  clusterRole: my-role
  removeRules:
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - '*'
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    verbs:
    - 'delete'
    - 'deletecollection'
    - 'patch'
    - 'update'
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - '*'
